modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="elemantal_imitation"
version="1.0.0"
displayName="elemantal imitation"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="edmun, MCreator"

[[dependencies.elemantal_imitation]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"




